### ISSUE TITLE
Errors in lumina_dmenu.rst

### ISSUE THREAD

**Issue by beanpole135** [vvheritagevv/bsdNotes#1]
Somebody just pointed out your notes about dmenu in lumina to me, and I spotted a few errors if you are interested in fixing them.
1. Keyboard shortcuts for launching applications in Lumina
   There are actually 2 built-in keyboard shortcuts for finding/launching apps. Alt-F2 is the traditional Fluxbox shortcut, and in Lumina that launches lumina-search for finding an application/file on demand (no mouse required). The second shortcut is a bit newer (0.9.1+ if I recall) and requires the new "Start Menu" plugin to be used: tap the Windows/Meta key to bring up the start menu, then start typing to automatically search for applications/binaries. Hitting enter once you found the right app will automatically launch it for you.
2. The ~/.fluxbox directory is where configs are placed if you actually logged into fluxbox (not Lumina). For older versions of Lumina (pre-0.9.1), the configs are located in `~/.lumina/fluxbox-*`, whereas with 0.9.1+ they are located in `${XDG_CONFIG_HOME}/lumina-desktop/fluxbox-*` (typically `~/.config/lumina-desktop/fluxbox-*`). The auto-reload mechanisms were also fixed up quite a bit in more recent versions so that modifying those files will automatically trigger fluxbox to reload it's configs.

Thanks!

**Comment by vvheritagevv** [comment]
Thanks for the input. I will add your notes to the file so that people can be fully informed.
